### ISSUE TITLE
Docs indicate a namespace import, but only a default import works

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint-community/eslint-plugin-es-x#157]
I set up a reproduction here: https://github.com/JoshuaKGoldberg/repros/tree/eslint-plugin-es-x-namespace-import. Going through the usage guide on https://eslint-community.github.io/eslint-plugin-es-x, we get:

```plaintext
Oops! Something went wrong! :(

ESLint: 9.1.1

TypeError: Key "rules": Key "es-x/no-async-iteration": Could not find "no-async-iteration" in plugin "es-x".
    at throwRuleNotFoundError (/Users/josh/repos/repros/node_modules/eslint/lib/config/rule-validator.js:66:11)
    at RuleValidator.validate (/Users/josh/repos/repros/node_modules/eslint/lib/config/rule-validator.js:147:17)
    at [finalizeConfig] (/Users/josh/repos/repros/node_modules/eslint/lib/config/flat-config-array.js:317:23)
    at FlatConfigArray.getConfig (/Users/josh/repos/repros/node_modules/@humanwhocodes/config-array/api.js:1036:55)
    at FlatConfigArray.isFileIgnored (/Users/josh/repos/repros/node_modules/@humanwhocodes/config-array/api.js:1060:15)
    at /Users/josh/repos/repros/node_modules/eslint/lib/eslint/eslint-helpers.js:346:57
    at Array.reduce (<anonymous>)
    at /Users/josh/repos/repros/node_modules/eslint/lib/eslint/eslint-helpers.js:333:36
    at /Users/josh/repos/repros/node_modules/eslint/lib/eslint/eslint-helpers.js:296:32
    at Object.isAppliedFilter (/Users/josh/repos/repros/node_modules/@nodelib/fs.walk/out/readers/common.js:12:31)
```

Switching the suggested import from a namespace import to a default import fixes the issue:

```diff
- import * as pluginESx from "eslint-plugin-es-x";
+ import pluginESx from "eslint-plugin-es-x";
```

Is this a docs bug or a functionality bug?

**Comment by ota-meshi** [comment]
Thank you for posting this issue!
I think it's a bug in the documentation :sweat: 
Another page uses the default import.
https://eslint-community.github.io/eslint-plugin-es-x/configs/
